# Generated by Django 6.0.4 on 2026-05-12 08:30

import django.db.models.deletion
import django.utils.timezone
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                (
                    "model",
                    models.CharField(
                        choices=[("C", "Cobotta"), ("V", "VS-060")], max_length=1
                    ),
                ),
                ("port", models.IntegerField(default=0)),
                ("cameraip", models.GenericIPAddressField(default=0)),
                ("max_load", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "max_open_tool",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Robots",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("shared", models.BooleanField(default=False)),
                ("speed", models.IntegerField(default=1)),
                (
                    "pattern",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Circular"), ("X", "Cross"), ("L", "Linear")],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                ("points", models.TextField(blank=True, default=None, null=True)),
                (
                    "keywords",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=50),
                        blank=True,
                        default=None,
                        max_length=1019,
                        null=True,
                        size=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("shared", models.BooleanField(default=False)),
                ("position", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "keywords",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=50),
                        blank=True,
                        default=None,
                        max_length=1019,
                        null=True,
                        size=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("shared", models.BooleanField(default=False)),
                ("photo", models.TextField(blank=True, default=None, null=True)),
                ("contour", models.TextField(blank=True, default=None, null=True)),
                ("shape", models.TextField(blank=True, default=None, null=True)),
                ("force", models.IntegerField(default=1)),
                ("height", models.FloatField(default=0.0)),
                (
                    "keywords",
                    django_mysql.models.ListCharField(
                        models.CharField(max_length=50),
                        blank=True,
                        default=None,
                        max_length=1019,
                        null=True,
                        size=20,
                    ),
                ),
                (
                    "obj_length",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("obj_width", models.IntegerField(blank=True, default=None, null=True)),
                ("weight", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("code", models.TextField(blank=True, default=None, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("shared", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRobot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.robot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UserRobots",
            },
        ),
    ]
