# Generated by Django 6.0.4 on 2026-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-last_modified"]},
        ),
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="draft_workspace",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="published_workspace",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="signature",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("published_with_draft", "Published with Draft"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[("task", "Task"), ("macro_task", "Macro Task")],
                default="task",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="workspace",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
