DROP TABLE IF EXISTS trajectories;
DROP TABLE IF EXISTS points;

CREATE TABLE trajectories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE points (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  j1 FLOAT NOT NULL,
  j2 FLOAT NOT NULL,
  j3 FLOAT NOT NULL,
  j4 FLOAT NOT NULL,
  j5 FLOAT NOT NULL,
  j6 FLOAT NOT NULL,
  hand FLOAT NOT NULL,
  trajectory_id INTEGER NOT NULL,
  FOREIGN KEY (trajectory_id) REFERENCES trajectories (id)
);